--Tạo database
USE LEARN_SQL
GO

CREATE TABLE LOPHOC
(
	MALOP CHAR(2) PRIMARY KEY,
	TENLOP VARCHAR(4)
)

CREATE TABLE HOCSINH
(
	MALOP CHAR(2),
	TEN NVARCHAR(100) NOT NULL UNIQUE,
	TUOI INT
)	
ALTER TABLE dbo.HOCSINH ADD CONSTRAINT PK_HOCSINH PRIMARY KEY(TEN)
--Bài học
--1. Thêm khoá ngoại bên ngoài bảng
ALTER TABLE dbo.HOCSINH ADD CONSTRAINT FK_MALOP_LOPHOC FOREIGN KEY(MALOP) REFERENCES dbo.LOPHOC(MALOP)
--2. Huỷ khoá ngoại
ALTER TABLE dbo.HOCSINH DROP CONSTRAINT FK_MALOP_LOPHOC